name: build-examples
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build examples
        run: |
          for dir in examples/*/; do
            example="./${dir%/}"
            nix flake update --flake "$example"
            nix build "$example#sandbox"
          done
