name: mdbook
on:
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: nix profile install .#ci
      - name: Check typos
        run: typos docs/src
      - name: Check markdown files
        run: markdownlint-cli2 "docs/src/**/*.md"
      - name: Check links
        run: lychee --no-progress docs/src
